### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by Annoyedbark73** [MilkyOnOurWay/MilkieServer#75]
What is this about/for

**Comment by Chedda98** [comment]
Hi! We are SOPT, where Korean university students gather to make IT-related services! Here, we made Milky Way through a project called App Jam. Milkway is a service that provides the location of a milk-related cafe for users with lactose intolerance. In addition to that, decaffeinated products are provided. We have a demo day this Saturday! It's going to be done online, so if you're curious, would you like to come? Participation fee is free and our team starts around 2:30 pm in Korean time! If you're interested, leave a comment below! I'll send you a link to sign up!

**Comment by dudgns3tp** [comment]
🤓

**Comment by kyhsa93** [comment]
@Annoyedbark73 i close this issue. if need more help, please reopen this. thank you
